version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_DB: user-management
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"